

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "MySignalr.DAL\App.config"
//     Connection String Name: "DefaultConnection"
//     Connection String:      "server=192.168.1.172;uid=sa;pwd=123456;Pooling=false;database=MySignalr"
// ------------------------------------------------------------------------------------------------
