// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace MySignalr.DAL.DbModels
{
    // UserInfo
    public partial class UserInfoConfiguration : EntityTypeConfiguration<UserInfo>
    {
        public UserInfoConfiguration()
            : this("dbo")
        {
        }
 
        public UserInfoConfiguration(string schema)
        {
            ToTable(schema + ".UserInfo");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.Account).HasColumnName("Account").IsRequired().HasColumnType("nvarchar").HasMaxLength(16);
            Property(x => x.PassWord).HasColumnName("PassWord").IsRequired().HasColumnType("nvarchar").HasMaxLength(16);
            Property(x => x.AddTime).HasColumnName("AddTime").IsRequired().HasColumnType("datetime");
            Property(x => x.AddIp).HasColumnName("AddIp").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(20);
            Property(x => x.AddDevices).HasColumnName("AddDevices").IsOptional().HasColumnType("nvarchar").HasMaxLength(20);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
